# Keep PDF in repo; put aux where LaTeX/biber agree
use Cwd qw(abs_path);
use File::Spec;

my $repo_root = abs_path('..');
$out_dir = File::Spec->catdir($repo_root, 'out');
$aux_dir = File::Spec->catdir($repo_root, 'build');

# Tell latexmk this is a LuaLaTeX workflow
$pdf_mode = 4;

# Enable shell-escape, synctex, etc.
$force_mode   = 1;
$shell_escape = 1;
$synctex      = 1;
$interaction  = 'nonstopmode';

# --- Modified pdflatex command ---
$pdflatex = 'lualatex -interaction=nonstopmode -file-line-error %O %S';

# Force biber to read/write the aux dir
$bibtex = "biber --input-directory=\"$aux_dir\" --output-directory=\"$aux_dir\" %O %B";
