FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    biber \
    fontconfig \
    fonts-firacode \
    fonts-fira-mono \
    fonts-fira-sans \
    latexmk \
    make \
    perl \
    python3 \
    python3-pygments \
    texlive-bibtex-extra \
    texlive-extra-utils \
    texlive-fonts-extra \
    texlive-fonts-recommended \
    texlive-lang-english \
    texlive-latex-extra \
    texlive-luatex \
    texlive-pictures \
    texlive-science \
  && rm -rf /var/lib/apt/lists/*
